# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/training/7_series_clk_resources/completed/vhdl/wave_gen.cache/wt [current_project]
set_property parent.project_path C:/training/7_series_clk_resources/completed/vhdl/wave_gen.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/clk_div.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/wave_gen_pkg.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/clk_gen.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/clkx_bus.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/cmd_parse.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/dac_spi.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/debouncer.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/lb_ctl.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/meta_harden.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/out_ddr_flop.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/reset_bridge.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/resp_gen.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/rst_gen.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/samp_gen.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/samp_ram.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/to_bcd.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/uart_baud_gen.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/uart_rx.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/uart_rx_ctl.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/uart_tx.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/uart_tx_ctl.vhd
  C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/wave_gen.vhd
}
read_vhdl -library utilities_lib C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/imports/vhdl/string_utilities_synth_pkg.vhd
read_ip -quiet C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/ip/clk_core/clk_core.xci
set_property used_in_implementation false [get_files -all c:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/ip/clk_core/clk_core_board.xdc]
set_property used_in_implementation false [get_files -all c:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/ip/clk_core/clk_core.xdc]
set_property used_in_implementation false [get_files -all c:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/ip/clk_core/clk_core_ooc.xdc]

read_ip -quiet C:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo.xci
set_property used_in_implementation false [get_files -all c:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/training/7_series_clk_resources/completed/vhdl/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top wave_gen -part xc7k70tfbg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef wave_gen.dcp
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
