# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/training/7_series_clk_resources/completed/verilog/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo.xci
# IP: The module: 'char_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/training/7_series_clk_resources/completed/verilog/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/training/7_series_clk_resources/completed/verilog/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/training/7_series_clk_resources/completed/verilog/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/training/7_series_clk_resources/completed/verilog/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo.xci
# IP: The module: 'char_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/training/7_series_clk_resources/completed/verilog/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/training/7_series_clk_resources/completed/verilog/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/training/7_series_clk_resources/completed/verilog/wave_gen.srcs/sources_1/ip/char_fifo/char_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
