# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/input_interface/input_interface.xci
# IP: The module: 'input_interface' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/input_interface/input_interface_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_interface'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/input_interface/input_interface.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_interface'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/input_interface/input_interface.xci
# IP: The module: 'input_interface' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/input_interface/input_interface_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_interface'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/input_interface/input_interface.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_interface'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
