# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/tx_pll/tx_pll.xci
# IP: The module: 'tx_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/tx_pll/tx_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/tx_pll/tx_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/tx_pll/tx_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/tx_pll/tx_pll.xci
# IP: The module: 'tx_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/tx_pll/tx_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/tx_pll/tx_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/training/7_series_IO_resources/completed/verilog/ioserdes.srcs/sources_1/ip/tx_pll/tx_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tx_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
