set_property IOSTANDARD LVCMOS18 [get_ports {led_pins[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_pins[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_pins[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_pins[3]}]
set_property DRIVE 12 [get_ports {led_pins[0]}]
set_property DRIVE 12 [get_ports {led_pins[1]}]
set_property DRIVE 12 [get_ports {led_pins[2]}]
set_property DRIVE 12 [get_ports {led_pins[3]}]
set_property SLEW SLOW [get_ports {led_pins[0]}]
set_property SLEW SLOW [get_ports {led_pins[1]}]
set_property SLEW SLOW [get_ports {led_pins[2]}]
set_property SLEW SLOW [get_ports {led_pins[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_pins[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_pins[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_pins[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_pins[7]}]
set_property DRIVE 12 [get_ports {led_pins[4]}]
set_property DRIVE 12 [get_ports {led_pins[5]}]
set_property DRIVE 12 [get_ports {led_pins[6]}]
set_property DRIVE 12 [get_ports {led_pins[7]}]
set_property SLEW SLOW [get_ports {led_pins[4]}]
set_property SLEW SLOW [get_ports {led_pins[5]}]
set_property SLEW SLOW [get_ports {led_pins[6]}]
set_property SLEW SLOW [get_ports {led_pins[7]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports clk_pin_p]
set_property IOSTANDARD LVCMOS18 [get_ports dac_clr_n_pin]
set_property IOSTANDARD LVCMOS18 [get_ports dac_cs_n_pin]
set_property IOSTANDARD LVCMOS12 [get_ports lb_sel_pin]
set_property IOSTANDARD LVCMOS18 [get_ports rst_pin]
set_property IOSTANDARD LVCMOS18 [get_ports rxd_pin]
set_property IOSTANDARD LVCMOS18 [get_ports spi_clk_pin]
set_property IOSTANDARD LVCMOS18 [get_ports spi_mosi_pin]
set_property IOSTANDARD LVCMOS18 [get_ports txd_pin]
#  set_property LOC AK17 [get_ports clk_pin_p]
#  set_property LOC AB34 [get_ports dac_clr_n_pin]
#  set_property LOC AA34 [get_ports dac_cs_n_pin]
#  set_property LOC AN16 [get_ports lb_sel_pin]
#set_property LOC AP8 [get_ports {led_pins[0]}]
#set_property LOC H23 [get_ports {led_pins[1]}]
#set_property LOC P20 [get_ports {led_pins[2]}]
#set_property LOC P21 [get_ports {led_pins[3]}]
#set_property LOC N22 [get_ports {led_pins[4]}]
#set_property LOC M22 [get_ports {led_pins[5]}]
#set_property LOC R23 [get_ports {led_pins[6]}]
#  set_property LOC P23 [get_ports {led_pins[7]}]
#  set_property LOC AN8 [get_ports rst_pin]
#  set_property LOC K26 [get_ports rxd_pin]
#  set_property LOC AB29 [get_ports spi_clk_pin]
#  set_property LOC AA29 [get_ports spi_mosi_pin]
#set_property LOC G25 [get_ports txd_pin]
set_property IOB TRUE [all_fanin -only_cells -startpoints_only -flat [all_outputs]]

